const Menu = [
  { is_header: true, title: "ناوبری" },
  { path: "/dashboard", icon: "bi bi-cpu", title: "داشبورد" },
  { path: "/analytics", icon: "bi bi-bar-chart", title: "آمار" },
  {
    path: "/email",
    icon: "bi bi-envelope",
    title: "ایمیل",
    children: [
      { path: "/email/inbox", title: "صندوق ورودی" },
      { path: "/email/compose", title: "ارسال" },
      { path: "/email/detail", title: "جزئیات" },
    ],
  },
  { is_divider: true },
  { is_header: true, title: "اجزاء" },
  { path: "/widgets", icon: "bi bi-columns-gap", title: "ابزارک‌ها" },
  {
    path: "/ai",
    icon: "bi bi-stars",
    title: "هوش مصنوعی",
    children: [
      { path: "/ai/chat", title: "گفت و گو" },
      { path: "/ai/image-generator", title: "تولید تصویر" },
    ],
  },
  {
    path: "/pos",
    icon: "bi bi-bag-check",
    title: "سیستم پوز",
    highlight: true,
    children: [
      { path: "/pos/customer-order", title: "سفارش مشتری" },
      { path: "/pos/kitchen-order", title: "سفارش آشپزخانه" },
      { path: "/pos/counter-checkout", title: "پیشخوان پرداخت" },
      { path: "/pos/table-booking", title: "رزرو میز" },
      { path: "/pos/menu-stock", title: "موجودی انبار" },
    ],
  },
  {
    path: "/ui",
    icon: "fa fa-heart",
    title: "جعبه‌ابزار رابط کاربری",
    children: [
      { path: "/ui/bootstrap", title: "Bootstrap" },
      { path: "/ui/buttons", title: "دکمه‌ها" },
      { path: "/ui/card", title: "کارت‌ها" },
      { path: "/ui/icons", title: "آیکون‌ها" },
      { path: "/ui/modal-notifications", title: "مودال و اطلاعیه" },
      { path: "/ui/typography", title: "نوشتار" },
      { path: "/ui/tabs-accordions", title: "تب و آکاردئون" },
    ],
  },
  {
    path: "/form",
    icon: "bi bi-pen",
    title: "فرم‌ها",
    children: [
      { path: "/form/elements", title: "اجزاء فرم" },
      { path: "/form/plugins", title: "افزودنی‌های فرم" },
      { path: "/form/wizards", title: "نصب‌کننده‌ها" },
    ],
  },
  {
    path: "/table",
    icon: "bi bi-grid-3x3",
    title: "جداول",
    children: [
      { path: "/table/elements", title: "اجزاء جدول" },
      { path: "/table/plugins", title: "افزودنی‌های جدول" },
    ],
  },
  {
    path: "/chart",
    icon: "bi bi-pie-chart",
    title: "نمودارها",
    children: [
      { path: "/chart/chart-js", title: "Chart.js" },
      { path: "/chart/chart-apex", title: "Apexcharts.js" },
    ],
  },
  { path: "/map", icon: "bi bi-compass", title: "نقشه" },
  {
    path: "/layout",
    icon: "bi bi-layout-sidebar",
    title: "چیدمان",
    children: [
      { path: "/layout/starter-page", title: "صفحه شروع" },
      { path: "/layout/fixed-footer", title: "Fixed Footer" },
      { path: "/layout/full-height", title: "Full Height" },
      { path: "/layout/full-width", title: "Full Width" },
      { path: "/layout/boxed-layout", title: "Boxed Layout" },
      { path: "/layout/collapsed-sidebar", title: "Collapsed Sidebar" },
      { path: "/layout/top-nav", title: "Top Nav" },
      { path: "/layout/mixed-nav", title: "Mixed Nav" },
      {
        path: "/layout/mixed-nav-boxed-layout",
        title: "Mixed Nav Boxed Layout",
      },
    ],
  },
  {
    path: "/pages",
    icon: "bi bi-collection",
    title: "صفحات",
    children: [
      { path: "/pages/scrum-board", title: "اسکرام بورد" },
      { path: "/pages/products", title: "محصولات" },
      { path: "/pages/product-details", title: "جزئیات محصول" },
      { path: "/pages/orders", title: "سفارشات" },
      { path: "/pages/order-details", title: "جزئیات سفارش" },
      { path: "/pages/gallery", title: "گالری" },
      { path: "/pages/search-results", title: "نتایج جستجو" },
      { path: "/pages/coming-soon", title: "به زودی" },
      { path: "/pages/error", title: "خطای ۴۰۴" },
      { path: "/pages/login", title: "ورود" },
      { path: "/pages/register", title: "ثبت‌نام" },
      { path: "/pages/messenger", title: "پیام‌رسان" },
      { path: "/pages/data-management", title: "مدیریت داده" },
      { path: "/pages/file-manager", title: "مدیریت فایل" },
      { path: "/pages/pricing", title: "قیمت" },
    ],
  },
  { path: "/landing", icon: "bi bi-diagram-3", title: "صفحه فرود" },
  { is_divider: true },
  { is_header: true, title: "کاربران" },
  { path: "/profile", icon: "bi bi-people", title: "پروفایل" },
  { path: "/calendar", icon: "bi bi-calendar4", title: "تقویم" },
  { path: "/settings", icon: "bi bi-gear", title: "تنظیمات" },
  { path: "/helper", icon: "bi bi-gem", title: "راهنما" },
];

export default Menu;
